### ISSUE TITLE
Make an opam package

### ISSUE THREAD

**Issue by gmalecha** [mit-plv/bbv#16]
We should make an opam package for this (once the PRs are merged).

**Comment by samuelgruetter** [comment]
Personally, I'm not a big fan of opam, but I do want bbv to be as useful as possible to as many people as possible, so if someone wants an opam package, we should make one.

@gmalecha is it possible to add code to make an opam package without interfering with the workflow of those who do not want to use opam in their daily development? As in, could you do that by adding a few lines to the makefile, and maybe some additional files? Or will you need bigger structural changes?

**Comment by gmalecha** [comment]
You don't need to do anything in the repo to make a package.

**Comment by samuelgruetter** [comment]
Interesting! So if you publish an opam package for bbv at some URL, and someone wants to know which commands were used to create that package, where can they find this information?

**Comment by JasonGross** [comment]
I believe the standard way to make something an opam package for Coq is to add the relevant files to the opam-coq-archive GitHub repo telling opam how to build and install the library.  We have packages for fiat and fiat-crypto (mostly for benching purposes) and I imagine template-coq has a package too.

**Comment by gmalecha** [comment]
i forgot that in order to make a package, I need to make a release version of the library. This means that I need contributor access to the repository. The alternative is to fork it and release from my fork (pulling in updates as things evolve). The later seems sub-optimal unless there is minimal desire to maintain bbv going forward.

**Comment by samuelgruetter** [comment]
just gave @gmalecha write access to this repo

**Comment by pedrotst** [comment]
I guess this should be closed.
