### ISSUE TITLE
Update opam package

### ISSUE THREAD

**Issue by gmalecha** [mit-plv/bbv#25]
Are people ok with me cutting a new release that is compatible with coq-8.9 and making an opam package for it?

**Comment by samuelgruetter** [comment]
Sure!

**Comment by skeuchel** [comment]
Would you consider cutting a new release? Just so that there is something in coq-released that builds with coq 8.11 and 8.12.

**Comment by samuelgruetter** [comment]
I don't know how to create opam packages, and I'm not using bbv any more, but maybe @gmalecha can do the same as for coq 8.9?

**Comment by JasonGross** [comment]
The first step is to create a new release at https://github.com/mit-plv/bbv/releases .  The next step is to copy over the opam files and make a PR at https://github.com/coq/opam-coq-archive

**Comment by samuelgruetter** [comment]
So I just added Coq 8.10 - 8.12 to the CI, and made a [new release](https://github.com/mit-plv/bbv/releases/tag/v1.2). Then I went to https://github.com/coq/opam-coq-archive to make a PR, but I saw there's already https://github.com/coq/opam-coq-archive/pull/1449 -- is this all that was needed?

**Comment by skeuchel** [comment]
Cool, thanks for taking care of this. The above PR was for the dev version. For the 1.2 release, you'd have to add the new version here https://github.com/coq/opam-coq-archive/tree/master/released/packages/coq-bbv. But this is something that I can do if you want.

**Comment by samuelgruetter** [comment]
Thanks @JasonGross and @skeuchel for explaining me opam :)
Just opened a [PR](https://github.com/coq/opam-coq-archive/pull/1451) in opam-coq-archive, could you please check if I got the opam file right?

**Comment by skeuchel** [comment]
Yeah, you got the opam file right and it has already been merged. Thanks again for your swift response.
