### ISSUE TITLE
need coq 8.18 compatible release

### ISSUE THREAD

**Issue by vzaliva** [mit-plv/bbv#48]
The current git version builds with coq-8.18. Could we please have a new release in OPAM? Thanks!

**Comment by samuelgruetter** [comment]
I just clicked some buttons to create this release on GitHub: https://github.com/mit-plv/bbv/releases/tag/v1.4
I don't really use opam for coq packages myself, nor do I know how to create opam packages, but there exists now https://github.com/mit-plv/bbv/archive/refs/tags/v1.4.zip so if that's useful for someone to make it available on opam, I won't object :slightly_smiling_face:

**Comment by vzaliva** [comment]
Looping in @gmalecha who is listed as Opam package maintainer

**Comment by vzaliva** [comment]
Created PR for OPAM package: https://github.com/coq/opam/pull/2782

**Comment by vzaliva** [comment]
thanks for the release!
