### ISSUE TITLE
New release for Coq 8.19?

### ISSUE THREAD

**Issue by MackieLoeffel** [mit-plv/bbv#50]
Would it be possible to create a new release? The last release (v1.4) is not compatible with Coq 8.19. The current master branch already compiles with Coq 8.19, so it should just be a matter of creating the release for opam.

**Comment by samuelgruetter** [comment]
Does [this](https://github.com/mit-plv/bbv/releases/tag/v1.5) do the job?

**Comment by MackieLoeffel** [comment]
I think that should do it, thanks for the quick response! I created https://github.com/coq/opam/pull/2981 to add the package to the coq-released opam repository.
